---
title: Music and the mind of the world
url: http://musicandthemindofthe.world
timezone: America/New_York
collections:
  logos:
    title: Logos
    output: true
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: default
description: From 1976 to 1982, Tony Conrad created “Music and the Mind of the World,”
  a piano composition comprising over 200 hours of recorded music. During this time
  everything Conrad played on the piano was recorded (with the incidental exception
  of perhaps three or four hours).
permalink: pretty
image: "/images/facebook-image.png"
