---
title: Music and the mind of the world
url: http://mmw.siteleaf.net
timezone: America/New_York
collections:
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: default
permalink: pretty
